name: Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  unit-tests:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: npm ci --prefix ui

      - name: eslint
        run: npm run eslint:ci --prefix ui

      - name: Validate i18n
        run: npm run validate-i18n --prefix ui

      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: ui
          # TODO compare with master
